# This is a basic workflow to help you get started with Actions

name: CI

# Runs on all pushes and pull requests to all branches
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Use a go environment
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          stable: true

      # Run tests
      - name: Run go tests
        run: go test ./scripts
